#include <mach/gpio.h>

static struct gpio_table picasso_E2_gpio_unused_init_table[] = {
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP1_DIN
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPDIF_IN
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPDIF_OUT
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPI1_MOSI
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPI1_SCK
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPI2_CS0_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPI2_SCK
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP3_DIN
	GPIO_CONFIG(NULL, TEGRA_GPIO_PO3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_DATA2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PO6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_DATA5
	GPIO_CONFIG(NULL, TEGRA_GPIO_PO7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_DATA6
	GPIO_CONFIG(NULL, TEGRA_GPIO_PO0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_DATA7
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PBB03
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PBB04
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PBB06
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PCC1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PCC2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_CS4_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_CS7_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_RST_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_WAIT
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CRT_HSYNC
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CRT_VSYNC
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DDC_SCL
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DDC_SDA
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // HDMI_INT
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_CS0_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_CS1_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_18
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_19
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_20
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_21
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_22
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_23
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_DC0
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_M1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PB2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_PWR0
	GPIO_CONFIG(NULL, TEGRA_GPIO_PC1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_PWR1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PZ4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_SCK
	GPIO_CONFIG(NULL, TEGRA_GPIO_PZ2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_SDIN
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_SDOUT
	GPIO_CONFIG(NULL, TEGRA_GPIO_PZ3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_WR_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // PEX_L2_CLKREQ_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PDD7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // PEX_L2_PRSNT_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // PEX_L2_RST_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PDD3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // PEX_WAKE_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK2_REQ
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PV2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PV3
	GPIO_CONFIG(NULL, TEGRA_GPIO_PD0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC3_DAT5
	GPIO_CONFIG(NULL, TEGRA_GPIO_PD3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC3_DAT6
	GPIO_CONFIG(NULL, TEGRA_GPIO_PD4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC3_DAT7
	GPIO_CONFIG(NULL, TEGRA_GPIO_PEE3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // HDMI_CEC
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_COL5
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_COL6
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_COL7
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW11
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW12
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW14
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW3
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW4
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW6
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW7
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_ROW9
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // OWR
	GPIO_CONFIG(NULL, TEGRA_GPIO_PZ5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SYS_CLK_REQ
	GPIO_CONFIG(NULL, TEGRA_GPIO_PEE1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK3_REQ
	GPIO_CONFIG(NULL, TEGRA_GPIO_PU4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GPIO_PU4
};

static struct gpio_table picasso_E2_gpio_sleep_init_table[] = {
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK1_OUT (AUDIO_CLK)
#if !defined(CONFIG_ACER_ES305)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP1_FS (AUDIO_RST#)
#endif
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP1_SCLK (AUDIO_SEL)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PA4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP2_DIN (AUDIO_DIN2)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PA5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP2_DOUT (AUDIO_DOUT2)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PA2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP2_FS (AUDIO_FS2)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PA3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP2_SCLK (AUDIO_SCLK2)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SPI2_MOSI (EN_ES305_OSC)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PP1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP3_DIN (CAM_LED_EN_NV)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_CLK (AUDIO_UART4_TX)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // ULPI_DIR (AUDIO_UART4_RX)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CAM_MCLK (CAM_MCLK)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_A16 (VIB_EN_T30S)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_AD10 (EN_T30S_FUSE_3V3)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_AD9 (DISPOFF#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // GMI_WAIT (3G_DISABLE#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB7,GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), // GPIO_PBB7 (3G_DISABLE2#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK2_OUT (CP_GPIO)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PZ0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_CLK (SDMMC_CLK)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PZ1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_CMD (SDMMC_CMD)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_DAT0 (SDMMC_DAT0)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_DAT1 (SDMMC_DAT1)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_DAT2 (SDMMC_DAT2)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PY4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC1_DAT3 (SDMMC_DAT3)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PCC4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // SDMMC4_CLK (EMMC_CLK)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PT7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_CMD (EMMC_CMD)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT0 (EMMC_DA0)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT1 (EMMC_DA1)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT2 (EMMC_DA2)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA3, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT3 (EMMC_DA3)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT4 (EMMC_DA4)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT5 (EMMC_DA5)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT6 (EMMC_DA6)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PAA7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // SDMMC4_DAT7 (EMMC_DA7)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PCC3, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), // SDMMC4_RST_N (EMMC_RST#)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PA0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK_32K_OUT (CLK_32K_OUT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // KB_COL4 (BOARD_ID_WP)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PEE0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // CLK3_OUT (CLK_12M_ES305)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP4_DIN (BT_PCM_IN)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP4_DOUT (BT_PCM_OUT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP4_FS (BT_PCM_SYNC)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // DAP4_SCLK (BT_PCM_CLK)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PJ5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // UART2_CTS_N (GPS_UART_CTS#)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PJ6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // UART2_RTS_N (GPS_UART_RTS#)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PC3, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), // UART2_RXD (GPS_UART_RXD )
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PC2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // UART2_TXD (GPS_UART_RXD)

	// Input pins
	GPIO_CONFIG(NULL, TEGRA_GPIO_PN2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //DAP1_DOUT (ES305_INT_R)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //SPI1_MISO (COMPASS_DRDY)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX3, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //SPI2_CS0_N (LIGHT_INT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW2, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //SPI2_CS1_N (HP_DET#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PW3, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //SPI2_CS2_N (CDC_IRQ#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //SPI2_MISO (GYRO_INT_R)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GPIO_PV0 (ON_KEY#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GPIO_PV1 (WAKE_UP_VBUS)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PO4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //ULPI_DATA3 (ULPI_DATA3)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PO5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //ULPI_DATA4 (SIM_DET)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GPIO_PBB6 (DOCK_DET#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD0 (NAND_D0)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD1 (BOOT_PD)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD2 (BOOT_PD)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG3, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD3 (BOOT_PD)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD4 (NAND_D4)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD5 (NAND_D5)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD6 (NAND_D6)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PG7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD7 (NAND_D7)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD12 (PCB_ID0)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD13 (PCB_ID1)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_AD14 (PCB_ID2)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_ADV_N (BOOT_PD)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_CLK (BOOT_PD)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ0, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //GMI_CS0_N (TS_INT#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ2, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //GMI_CS1_N (CHARGER_STAT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GMI_CS2_N (BOARD_ID0)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GMI_CS3_N (BOARD_ID1)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PK2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_CS4_N (POUT_3G_1)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI3, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //GMI_CS6_N (TEMP_ALERT#)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PI6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_CS7_N (POUT_WIFI)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI5, GPIO_ENABLE, GPIO_HIGH, GPIO_INPUT), //GMI_IORDY (POUT_3G)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_OE_N (FORCE_RECOVERY#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_WR_N (NOR_BOOT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_COL0 (SC_LOCK#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_COL1 (VOL_DOWN#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_COL2 (VOL_UP#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_ROW1 (BOARD_ID3)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS0, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_ROW8 (SHORT_DET)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_ROW10 (WF_WAKE#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //KB_ROW12 (SD_DET#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_ROW13 (G_ACC_INT)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //KB_ROW14 (LINE_OUT_DET#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PS7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //KB_ROW15 (BT_IRQ#)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PU5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GPIO_PU5 (DEBUG_UART1_RX_R)

	// I2C pins
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PBB1, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //CAM_I2C_SCL (CAM_I2C_SCL)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PBB2, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //CAM_I2C_SDA (CAM_I2C_SDA)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PT5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GEN2_I2C_SCL (GEN2_I2C_SCL)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PT6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GEN2_I2C_SDA (GEN2_I2C_SDA)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //DDC_SCL (DDC_SCL_R)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PV5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //DDC_SDA (DDC_SDA_R)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PZ6, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //PWR_I2C_SCL (PWR_I2C_SCL)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PZ7, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //PWR_I2C_SDA (PWR_I2C_SDA)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PC4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GEN1_I2C_SCL (GEN1_I2C_SCL)
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PC5, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GEN1_I2C_SCL (GEN1_I2C_SCL)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PB3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_PCLK (NV_LCD_PCLK)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PB1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GMI_A18 (EN_VDDLCD_T30S)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PB0, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GMI_A17 (TS_PWR_EN)
	GPIO_CONFIG(NULL, TEGRA_GPIO_PX6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //SP1_CS0_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PP3, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //DAP3_SCLK
	GPIO_CONFIG(NULL, TEGRA_GPIO_PY2, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //ULPI_NXT
	GPIO_CONFIG(NULL, TEGRA_GPIO_PY3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //ULPI_STP
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB0, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GPIO_PBB0
	GPIO_CONFIG(NULL, TEGRA_GPIO_PBB5, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GPIO_PBB5
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GMI_AD11
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH7, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GMI_AD15
	GPIO_CONFIG(NULL, TEGRA_GPIO_PH0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GMI_AD8
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK3, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_CS2_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PK4, GPIO_ENABLE, GPIO_LOW, GPIO_INPUT), //GMI_CS3_N
	GPIO_CONFIG(NULL, TEGRA_GPIO_PI2, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GMI_DQS
	GPIO_CONFIG(NULL, TEGRA_GPIO_PD1, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //SDMMC3_DAT4
	GPIO_CONFIG(NULL, TEGRA_GPIO_PQ3, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //KB_COL3
	GPIO_CONFIG(NULL, TEGRA_GPIO_PU3, GPIO_ENABLE, GPIO_HIGH, GPIO_OUTPUT), //GPIO_PU3
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D0
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D3
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D4
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D5
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D6
	GPIO_CONFIG(NULL, TEGRA_GPIO_PE7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D7
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D8
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D9
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D10
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF3, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D11
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF4, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D12
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D13
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D14
	GPIO_CONFIG(NULL, TEGRA_GPIO_PF7, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D15
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D16
	GPIO_CONFIG(NULL, TEGRA_GPIO_PM1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_D17
	GPIO_CONFIG(NULL, TEGRA_GPIO_PD2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_DC1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PJ1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //LCD_DE
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PR0, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //KB_ROW0
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //KB_ROW2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PR5, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //KB_ROW5
	//GPIO_CONFIG(NULL, TEGRA_GPIO_PU1, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GPIO_PU1
	GPIO_CONFIG(NULL, TEGRA_GPIO_PC6, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), // LCD_PWR2
	GPIO_CONFIG(NULL, TEGRA_GPIO_PU2, GPIO_ENABLE, GPIO_LOW, GPIO_OUTPUT), //GPIO_PU2
};
